package com.aexample.persistence.model;
// Generated Dec 4, 2015 1:44:19 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

//import com.aexa,[;ey.persistence.model.Role;
/**
 * Accounts generated by hbm2java
 */

import javax.persistence.*;

@SuppressWarnings("serial")
@Entity
@Table(name = "Accounts")
public class Accounts implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	
	@Column(name = "id")
	private Long id;

	@Column(name = "OrgName")
	private String orgName;

	@Column(name = "FirstName")
	private String firstName;

	@Column(name = "LastName")
	private String lastName;

	@Column(name = "Email")
	private String email;

	@Column(name = "LoginId")
	private String loginId;

	@Column(name = "Password")
	private String password;

	@Column(name = "ProfileComplete")
	private Boolean profileFlag;

	@Column(name = "Plan")
	private String plan;

	@Column(name = "Role")
	private String role;

	@Column(name = "AccountNonExpired")
	private Boolean accountNonExpired;

	@Column(name = "AccountNonLocked")
	private Boolean accountNonLocked;

	@Column(name = "CredentialsNonExpired")
	private Boolean credentialsNonExpired;

	@Column(name = "Enabled")
	private Boolean enabled;
	
	@Column(name="CreateDate")
	private Date createDate;

	public Accounts() {
	}

	public Accounts(Long id, String orgName, String firstName, String lastName, String email, String loginId,
			String password, Boolean profileFlag, String plan, String role, Boolean accountNonExpired,
			Boolean accountNonLocked, Boolean credentialsNonExpired, Boolean enabled, Date createDate) {
		this.id = id;
		this.orgName = orgName;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.loginId = loginId;
		this.password = password;
		this.profileFlag = false;
		this.plan = plan;
		this.role = role;

		this.accountNonExpired = accountNonExpired;
		this.accountNonLocked = accountNonLocked;
		this.credentialsNonExpired = credentialsNonExpired;
		this.enabled = enabled;
		this.createDate = createDate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getOrgName() {
		return this.orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getLoginId() {
		return this.loginId;
	}

	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Boolean getProfileFlag() {
		return this.profileFlag;
	}

	public void setProfileFlag(Boolean profileFlag) {
		this.profileFlag = profileFlag;
	}

	public String getPlan() {
		return this.plan;
	}

	public void setPlan(String plan) {
		this.plan = plan;
	}

	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public Boolean getAccountNonExpired() {
		return accountNonExpired;
	}

	public void setAccountNonExpired(Boolean accountNonExpired) {
		this.accountNonExpired = accountNonExpired;
	}

	public Boolean getAccountNonLocked() {
		return accountNonLocked;
	}

	public void setAccountNonLocked(Boolean accountNonLocked) {
		this.accountNonLocked = accountNonLocked;
	}

	public Boolean getCredentialsNonExpired() {
		return credentialsNonExpired;
	}

	public void setCredentialsNonExpired(Boolean credentialsNonExpired) {
		this.credentialsNonExpired = credentialsNonExpired;
	}

	public Boolean getEnabled() {
		return enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}
	
	public Date getCreateDate(){
		return createDate;
	}
	
	public void setCreateDate(Date createDate){
		this.createDate = createDate;
	}
	
}
