package com.aexample.persistence.model;
// Generated Aug 19, 2017 12:41:47 PM by Hibernate Tools 5.2.3.Final

/**
 * RolesPrivileges generated by hbm2java
 */
public class RolesPrivileges implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long roleId;

	public RolesPrivileges() {
	}

	public long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(long roleId) {
		this.roleId = roleId;
	}

}
