package com.aexample.persistence.model;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;



// Generated Aug 19, 2017 12:41:47 PM by Hibernate Tools 5.2.3.Final

/**
 * UserRoles generated by hbm2java
 */
@Entity
@Table(name = "user_roles")
public class UserRoles implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@NotNull
	private Long user_Id;
	
	@NotNull
	private Long role_Id;

	public UserRoles() {
	}

	public Long getUser_Id() {
		return this.user_Id;
	}

	public void setUser_Id(Long user_Id) {
		this.user_Id = user_Id;
	}

	public Long getRole_Id() {
		return this.role_Id;
	}

	public void setRole_Id(Long role_Id) {
		this.role_Id = role_Id;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (int) (role_Id ^ (role_Id >>> 32));
		result = prime * result + (int) (user_Id ^ (user_Id >>> 32));
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		UserRoles other = (UserRoles) obj;
		if (role_Id != other.role_Id)
			return false;
		if (user_Id != other.user_Id)
			return false;
		return true;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "UserRoles [user_Id=" + user_Id + ", role_Id=" + role_Id + "]";
	}
	
	
}
