package com.aexample.persistence.model;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;



// Generated Aug 19, 2017 12:41:47 PM by Hibernate Tools 5.2.3.Final

/**
 * UserRoles generated by hbm2java
 */
@Entity
@Table(name = "user_roles")
public class UserRoles implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@NotNull
	private long user_Id;
	
	@NotNull
	private long role_Id;

	public UserRoles() {
	}

	public long getUserId() {
		return this.user_Id;
	}

	public void setUserId(long user_Id) {
		this.user_Id = user_Id;
	}

	public long getRoleId() {
		return this.role_Id;
	}

	public void setRoleId(long role_Id) {
		this.role_Id = role_Id;
	}
	
	
}
